name: mcRP
version: 1.3.1 BETA 2
description: Lightweight MineCraft Roleplay

main: me.jacklin213.mcrp.mcRP

commands:
  mcrp:
    description: Main command
  class:
    description: Main class command
  binds:
    description: View skills that are item bound
  skills:
    description: View available skills and use a skill
  skillinfo:
    description: View detailed info about skills

permissions:
  mcrp.*:
    default: op
    description: Allows usage of all commands and bypasses
    children:
      mcrp.realism.*: true
      mcrp.reload: true
      mcrp.setmotd: true
      mcrp.skills.nocooldown: true
  mcrp.realism.*:
    default: op
    description: Exempt from all diseases and recieve all realism features
    children:
      mcrp.diseases.exempt.*: true
      mcrp.realism.bleed.exempt: true
      mcrp.realism.treedestroy: true
  mcrp.diseases.exempt.*:
    default: op
    description: Bypass all diseases
    children: 
      mcrp.diseases.dehydration.exempt: true
  
  mcrp.class.choose:
    description: Allows player to choose a class
    default: true    
  mcrp.diseases.dehydration.exempt: 
    description: Player is exempt from dehydration
    default: false
  mcrp.realism.bleed.exempt:
    description: Avoid bleeding
    default: false
  mcrp.realism.treedestroy:
    description: Destroy trees instantly with an axe
    default: false
  mcrp.reload:
    description: Reload plugin
    default: op
  mcrp.setmotd:
    description: Set message of the day
    default: op
  mcrp.skills.use:
    description: Allows the use of the skills command
    default: true
  mcrp.skills.info:
    description: Allows the use of the skillsinfo command
    default: true
  mcrp.skills.nocooldown:
    description: Allows player to have no cooldown for skills
    default: op