name: mcRP
version: 1.3
description: Lightweight MineCraft Roleplay

main: me.jacklin213.mcrp.mcRP

commands:
  mcrp:
    description: Information command
  binds:
    description: View skill aliases
  skills:
    description: View available skills and use a skill

permissions:
  mcrp.*:
    default: op
    description: Allows usage of all commands and bypasses
    children:
      mcrp.realism.*: true
      mcrp.reload: true
      mcrp.setwelcomemessage: true
      mcrp.skills.nocooldown: true
  mcrp.realism.*:
    default: op
    description: Exempt from all diseases and recieve all realism features
    children:
      mcrp.diseases.exempt.*: true
      mcrp.realism.bleed.exempt: true
      mcrp.realism.treedestroy: true
  mcrp.diseases.exempt.*:
    default: op
    description: Bypass all diseases
    children: 
      mcrp.diseases.dehydration.exempt: true
      
  mcrp.diseases.dehydration.exempt: 
    description: Player is exempt from dehydration
    default: false
  mcrp.realism.bleed.exempt:
    description: Avoid bleeding and diseases
    default: false
  mcrp.realism.treedestroy:
    description: Destroy trees instantly with an axe
    default: false
  mcrp.reload:
    description: Reload plugin
    default: op
  mcrp.setwelcomemessage:
    description: Set welcome message
    default: op
  mcrp.skill.nocooldown:
    description: Allows player to have no cooldown for skills
    default: op