name: mcRP
version: 1.0
description:
author: jacklin213
authors: [PineAbe]

main: me.jacklin213.mcrp.mcRP
commands:
#<<<<<<< HEAD
  test:
    description: test
  test2:
    description: test
#=======
#Im pretty sure you only need mcRP and not the rest of it. Thats how I did it on my lotto plugin
  mcRP:
    description: Displays info on mcRP
    usage: Correct usage /mcRP
  mcRP test:
    description: test
  mcRP test2:
    description: test
  mcRP reload:
    description: Reloads config file for mcRP
    usage: Correct usage /mcRP reload
    permission: mcRP.reload
    permission-message: You don't have the permission to reload the config!
  mcRP set welcomemessage:
    description: Sets the welcome message
    usage: Correct usage /mcRP set welcomemessage or /mcRP set wm
    permission: mcRP.setwelcomemessage
    permissions-message: You don't have the permission to set the welcome message!
  Skills:
    description: Shows all the Skills
    usage: Correct usage /skills

permissions:
  mcRP.*:
    description: Allows use of all mcRP commands
    default: op
    children:
      mcRP.setwelcomemessage: true
      mcRP.reload: true
  mcRP.setwelcomemessage:
    description: Allows people to set welcome message
    default: op
  mcRP.reload:
    description: Allows people to reload config
    default: op
#>>>>>>> Updated everything